# Simple workflow for deploying Vite site content to GitHub Pages
name: Deploy Vite Site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['master']  # Change this to your desired branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Change this to your desired Node.js version
          cache: 'npm'
          cache-dependency-path: vite-game/package-lock.json
      - name: Install dependencies
        run: npm install --prefix vite-game
      - name: Build
        run: npm run build --prefix vite-game
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload the built site from the subdirectory
          path: './vite-game/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
